### ISSUE TITLE
Lection request

### ISSUE THREAD

**Issue by ArMANIAK** [HowProgrammingWorks/Index#13]
Please, add lection about compiling and interpreting code in different programming languages. How it works, general principles. You've scratched this topic in lection about mono- and polymorphic code. Like, "compiler reads file, create a template (hidden class), then during run-time checks whether the arguements are of the same type. If so, compiler executes code through the template, else, it creates one more template"

**Comment by tshemsedinov** [comment]
Added to waiting list @ArMANIAK
